---
title: "Reproducible science workshop"
Subtitle: "Students reading instructions"
author: "[**_Gbadamassi G.O. Dossa_**](https://scholar.google.com/citations?user=w20AkZcAAAAJ&hl=en)"
date: "Updated on `r Sys.Date()` (created on 2021-09-13)"
output: 
#rmdformats::material
  html_document:
    fig_caption: yes
    theme: spacelab #readable #sandstone #spacelab #flatly
#    highlight: pygments #tango #kate
#    toc: TRUE
#    toc_depth: 3
#    number_sections: TRUE
#    toc_float:
#      collapsed: TRUE
#      smooth_scroll: TRUE
#      toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Prior to attending the workshop on reproducible science, students from AFEC-X are required to form a group of 2-3 members. Each group gets assigned a publication. This publication needs to be read for 45 minutes individually and members of each group then gather to discuss about 45 minutes during which they will answer the following questions:

1- What was the title of your article? (tip: look at the highlight sentence at the top of your pdf file)

2- How many people did you read the article with?

3- Cite one term that was new to you in your article (One term per person and define it)

4- How do these new terms of your group fit within the reproducible frame work?

5- What does the article stir up in your mind that you wish to know now?

6- What is the take home message from your article?

7- Write a quote from the article that you think summarizes the precedent take home message.

Use 30 minutes to make a powerpoint (PPT) presentation to deliver the answers of the above questions. Each presentation will 5 minutes (Presentation including questions).
